spring.application.name=spring-integration-file-transfer
# java-dsl / xml
spring.profiles.active=java-dsl
#spring.profiles.active=xml

# timestamp / uuid - refer to FileNamingStrategy.java enum
file.transfer.naming-strategy=timestamp
#file.transfer.naming-strategy=uuid

file.transfer.source-dir=./input
file.transfer.target-dir=./output
file.transfer.poll-interval-millis=2000
