spring.application.name=spring-integration-file-transfer
file.transfer.poll-interval-millis=2000

# Profiles - java-dsl / xml
spring.profiles.active=java-dsl
#spring.profiles.active=xml

# Naming Strategy - timestamp / uuid - refer to FileNamingStrategy.java enum
file.transfer.naming-strategy=timestamp
#file.transfer.naming-strategy=uuid

# base dirs
file.transfer.source-dir=./input
file.transfer.target-dir=./output

# routing
file.transfer.large-file-threshold-bytes=5000000
file.transfer.large-file-dir=large-files
file.transfer.categories=image,text
file.transfer.category.image.extensions=jpg,jpeg,png,gif
file.transfer.category.image.dir=images
file.transfer.category.text.extensions=txt,log,csv
file.transfer.category.text.dir=text